name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install frozen-flask
          pip list

      - name: Create build directory
        run: |
          mkdir -p build
          ls -la

      - name: Build static files
        run: |
          python freeze.py
          echo "Contents of build directory:"
          ls -la build/
          if [ ! -f "build/index.html" ]; then
            echo "Error: index.html not found in build directory"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: main
          force_orphan: true
          commit_message: "Deploy: ${{ github.event.head_commit.message }}" 