name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install frozen-flask
          pip list

      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Templates directory:"
          ls -la templates/
          echo "Static directory:"
          ls -la static/
          echo "Static/images directory:"
          ls -la static/images/
          echo "Image file details:"
          file static/images/profile.jpg

      - name: Create build directory structure
        run: |
          mkdir -p build/static/images
          ls -la build/

      - name: Build static files
        run: |
          echo "Running freeze.py..."
          python freeze.py
          echo "Contents of build directory:"
          ls -la build/
          if [ ! -f "build/index.html" ]; then
            echo "Error: index.html not found in build directory"
            ls -la build/
            exit 1
          fi

      - name: Copy static files
        run: |
          echo "Copying static files..."
          echo "Source image path:"
          ls -la static/images/profile.jpg
          cp -v static/images/profile.jpg build/static/images/
          echo "Destination image path:"
          ls -la build/static/images/profile.jpg
          echo "Contents of build/static directory:"
          ls -la build/static/
          echo "Contents of build/static/images directory:"
          ls -la build/static/images/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 